CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE secrets (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  secret TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
